import sausageCasseroleImage from '../assets/images/01-sausage-bean-casserole.png';
import chickenCacciatoreImage from '../assets/images/02-chicken-cacciatore.png';
import beefChilliImage from '../assets/images/03-beef-chilli.png';
import beefOrzoImage from '../assets/images/04-beef-tomato-orzo.png';
import chickpeaStewImage from '../assets/images/05-chickpea-sweet-potato-stew.png';

export const seedRecipes = [
  {id:'sausage-casserole',title:'Sausage Tomato & Chickpea Casserole',image:sausageCasseroleImage,type:'Slow cooker',time:'6–7 hrs',serves:2,expense:2,taste:0,description:'A rich, smoky casserole with browned sausages, sweet peppers and a thick tomato sauce.',ingredients:['454g pork sausages','1 onion, sliced','1 pepper, chopped','1 carrot, sliced','400g chopped tomatoes','200g chickpeas, drained','1 tbsp tomato purée','1 tsp smoked paprika','1 tsp mixed herbs','½ chicken stock cube','1 tsp Worcestershire sauce'],steps:['Brown the sausages in a frying pan for 5 minutes.','Put the onion, pepper and carrot in the slow cooker. Arrange the sausages on top.','Add the tomatoes, chickpeas, tomato purée, paprika, herbs, stock and Worcestershire sauce.','Cook on low for 6–7 hours or high for 3–4 hours.','If the sauce is thin, remove the lid and cook on high for the final 20 minutes. Season to taste.']},
  {id:'chicken-cacciatore',title:'Chicken Cacciatore with Potatoes',image:chickenCacciatoreImage,type:'Slow cooker',time:'6 hrs',serves:2,expense:2,taste:0,description:'Tender chicken thighs cooked with peppers, mushrooms and potatoes in a herby tomato sauce.',ingredients:['420g chicken thigh fillets','350g baby potatoes, halved','1 onion, sliced','1 pepper, sliced','150g mushrooms, sliced','400g chopped tomatoes','150ml passata','1 tsp garlic purée','1 tsp mixed herbs','½ chicken stock cube','Black pepper'],steps:['Place the potatoes, onion, pepper and mushrooms in the slow cooker.','Season the chicken and lay it over the vegetables.','Mix the tomatoes, passata, garlic, herbs and stock cube. Pour over the chicken.','Cook on low for 6 hours or high for 3–4 hours.','Lift the chicken onto warm plates, stir the sauce and season to serve.']},
  {id:'beef-chilli',title:'Slow Cooker Beef Chilli',image:beefChilliImage,type:'Slow cooker',time:'6–7 hrs',serves:2,expense:2,taste:0,description:'A deeply tomatoey chilli with beef, kidney beans and gentle smoky heat.',ingredients:['250g lean beef mince','1 onion, diced','1 pepper, diced','1 carrot, diced','400g chopped tomatoes','400g kidney beans, drained','1 tbsp tomato purée','1 tsp mild chilli powder','1 tsp smoked paprika','1 tsp garlic purée','½ beef stock cube','140g long grain rice'],steps:['Brown the mince in a frying pan and drain excess fat.','Put the onion, pepper and carrot in the slow cooker, then add the beef.','Stir in the tomatoes, beans, tomato purée, spices, garlic and stock.','Cook on low for 6–7 hours or high for 3–4 hours.','Cook the rice separately, season the chilli and serve.']},
  {id:'beef-orzo',title:'One Pot Beef & Tomato Orzo',image:beefOrzoImage,type:'One pot',time:'35 min',serves:2,expense:2,taste:0,description:'A glossy, comforting one-pot pasta with beef, vegetables and plenty of tomato flavour.',ingredients:['250g lean beef mince','1 onion, diced','1 carrot, diced','1 pepper, diced','400g chopped tomatoes','200ml passata','150g orzo','1 tsp garlic purée','1 tsp mixed herbs','1 beef stock cube','1 tsp Worcestershire sauce'],steps:['Brown the mince in a deep pan. Add the vegetables and cook for 5 minutes.','Stir in the garlic and herbs, then add tomatoes, passata, stock and Worcestershire sauce.','Add the orzo and simmer uncovered for 12–15 minutes, stirring often.','Add a splash of water whenever the pan looks dry.','Season and rest for 5 minutes before serving.']},
  {id:'chickpea-stew',title:'Smoky Chickpea & Sweet Potato Stew',image:chickpeaStewImage,type:'Slow cooker',time:'6 hrs',serves:2,expense:1,taste:0,description:'A vibrant vegetarian stew with sweet potato, chickpeas and peppers in a smoky tomato broth.',ingredients:['400g sweet potato, cubed','200g chickpeas, drained','1 onion, diced','1 pepper, chopped','1 carrot, sliced','400g chopped tomatoes','1 tsp garlic purée','1 tsp smoked paprika','½ tsp mild chilli powder','1 tsp mixed herbs','½ vegetable stock cube'],steps:['Put the sweet potato, chickpeas, onion, pepper and carrot in the slow cooker.','Add the tomatoes, garlic, paprika, chilli, herbs and stock. Stir well.','Cook on low for 6 hours or high for 3–4 hours.','Mash a few sweet potato cubes against the side and stir through to thicken.','Taste, season and serve in warm bowls.']},
  {id:'viral-doner-kebab',title:'Homemade Döner Kebab Pitas',image:'',type:'Oven',time:'35 min',serves:4,expense:2,taste:0,description:'Tender, warmly spiced beef döner baked in parchment and tucked into warm pitas with roast tomatoes, peppers and cooling sauces.',ingredients:['1 onion, roughly chopped','2 garlic cloves','454g beef mince','1 tbsp tomato purée','2 tbsp Greek yoghurt','1 tsp ground cumin','1 tsp paprika','¼ tsp red pepper flakes (optional)','1 tsp salt','½ tsp black pepper','3 tomatoes, quartered','2 green peppers','1 tbsp olive oil','4 pita breads','Chilli sauce, to serve','Garlic-yoghurt mayo sauce, to serve'],steps:['Heat the oven to 204°C and line a large baking tray.','Blend the onion and garlic to a smooth purée, keeping all the liquid.','Mix the onion purée with the beef, tomato purée, Greek yoghurt, cumin, paprika, chilli flakes, salt and pepper for 1–2 minutes until thoroughly combined.','Divide the meat into three equal pieces. Place each piece between sheets of baking parchment and roll it into an even rectangle.','Remove the top sheet, then roll each meat rectangle tightly from a short edge with the bottom parchment still attached. Put all three rolls on the tray.','Add the tomatoes and peppers alongside the rolls, drizzle the vegetables with olive oil and season lightly.','Bake for 15–20 minutes until the meat is cooked and lightly browned. Rest for 5 minutes, unwrap and tear into generous strips.','Warm the pita breads, fill with döner meat and roasted vegetables, then finish with chilli sauce and garlic-yoghurt mayo sauce.']}
];
